GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order Pizza"
}

###

DELETE http://localhost:3001/todo/delete/6450583ba9f26314dd3dd487

###
PUT http://localhost:3001/todo/complete/64505827a9f26314dd3dd485
